swagger: '2.0'
info:
  version: '1.0'
  title: FaibaMobile
  description: faiba mobile APIs
  contact: {}
host: 192.168.47.7:8243
basePath: /faiba/mobile/v3
securityDefinitions:
  auth:
    type: oauth2
    flow: implicit
    authorizationUrl: http://example.com/auth
    scopes: {}
schemes:
- https
- http
consumes:
- application/json
produces:
- application/json
paths:
  /DFaibaBalance:
    post:
      description: 'TODO: Add Description'
      summary: Sub Balance
      tags:
      - DFaibaBalance
      operationId: DFaibaBalancePost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/SubBalanceRequest'
      responses:
        200:
          description: ''
          headers: {}
  /DFaibaBundlesTopup:
    post:
      description: 'TODO: Add Description'
      summary: Buy Bundles
      tags:
      - DFaibaBundlesTopup
      operationId: DFaibaBundlesTopupPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/BuyBundlesRequest'
      responses:
        200:
          description: ''
          schema:
            $ref: '#/definitions/SuccessBundlePurchase'
          examples:
            application/json:
              status: 1
              message: success
              time: 1534789445
              Result:
                TransactionSN: 1534789444
          headers:
            Access-Control-Allow-Headers:
              type: string
              default: authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction
            Access-Control-Allow-Methods:
              type: string
              default: POST
            Access-Control-Allow-Origin:
              type: string
              default: '*'
            Cache-Control:
              type: string
              default: no-cache, private
            Connection:
              type: string
              default: keep-alive
            Date:
              type: string
              default: Mon, 20 Aug 2018 18:24:07 GMT
            Transfer-Encoding:
              type: string
              default: chunked
            X-RateLimit-Limit:
              type: string
              default: 6000000
            X-RateLimit-Remaining:
              type: string
              default: 5999997
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/InsufficentBalance'
          examples:
            application/json:
              status: -1
              message: '[S-ACT-00049] [Balance is not enough or no effective balance.] '
              time: 1534789547
              Result: ''
  /DFaibaRecharge:
    post:
      description: 'TODO: Add Description'
      summary: TopUp
      tags:
      - DFaibaRecharge
      operationId: DFaibaRechargePost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/TopUpRequest'
      responses:
        200:
          description: ''
          headers: {}
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/InvalidUserCode'
          examples:
            application/json:
              status: -1
              message: invalid userCode
              time: 1534789703
              ref: LLL0SSWQ60
  /DFaibacheckout:
    post:
      description: 'TODO: Add Description'
      summary: Mpesa Checkout Bundles
      tags:
      - DFaibacheckout
      operationId: DFaibacheckoutPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          type: string
      responses:
        200:
          description: ''
          headers: {}
  /DFaibaAirtimecheckout:
    post:
      description: 'TODO: Add Description'
      summary: Mpesa Checkout
      tags:
      - DFaibaAirtimecheckout
      operationId: DFaibaAirtimecheckoutPost
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          type: string
      responses:
        200:
          description: ''
          headers: {}
definitions:
  SubBalanceRequest:
    title: SubBalanceRequest
    example:
      msisdn: 254747018220
    type: object
    properties:
      msisdn:
        type: integer
        format: int64
    required:
    - msisdn
  BuyBundlesRequest:
    title: BuyBundlesRequest
    example:
      msisdn: 254747018220
      code: DailyData1GB
    type: object
    properties:
      msisdn:
        type: integer
        format: int64
      code:
        type: string
    required:
    - msisdn
    - code
  SuccessBundlePurchase:
    title: SuccessBundlePurchase
    example:
      status: 1
      message: success
      time: 1534789445
      Result:
        TransactionSN: 1534789444
    type: object
    properties:
      status:
        type: integer
        format: int32
      message:
        type: string
      time:
        type: integer
        format: int32
      Result:
        $ref: '#/definitions/Result'
    required:
    - status
    - message
    - time
    - Result
  Result:
    title: Result
    example:
      TransactionSN: 1534789444
    type: object
    properties:
      TransactionSN:
        type: string
    required:
    - TransactionSN
  InsufficentBalance:
    title: InsufficentBalance
    example:
      status: -1
      message: '[S-ACT-00049] [Balance is not enough or no effective balance.] '
      time: 1534789547
      Result: ''
    type: object
    properties:
      status:
        type: integer
        format: int32
      message:
        type: string
      time:
        type: integer
        format: int32
      Result:
        type: string
    required:
    - status
    - message
    - time
    - Result
  TopUpRequest:
    title: TopUpRequest
    example:
      msisdn: 254747018220
      amount: 1
      refno: LLL0SSWQ60
      paymentCode: mpesa
      userCode: agent@yourdomian.com
      transSerial: 1516725113
      userHash: GFDG7454645b4v545c45M==
    type: object
    properties:
      msisdn:
        type: string
      amount:
        type: string
      refno:
        type: string
      paymentCode:
        type: string
      userCode:
        type: string
      transSerial:
        type: string
      userHash:
        type: string
    required:
    - msisdn
    - amount
    - refno
    - paymentCode
    - userCode
    - transSerial
    - userHash
  InvalidUserCode:
    title: InvalidUserCode
    example:
      status: -1
      message: invalid userCode
      time: 1534789703
      ref: LLL0SSWQ60
    type: object
    properties:
      status:
        type: integer
        format: int32
      message:
        type: string
      time:
        type: integer
        format: int32
      ref:
        type: string
    required:
    - status
    - message
    - time
    - ref
security:
- auth: []
tags:
- name: DFaibaBalance
  description: Folder for DFaibaBalance
- name: DFaibaBundlesTopup
  description: Folder for DFaibaBundlesTopup
- name: DFaibaRecharge
  description: Folder for DFaibaRecharge
- name: DFaibacheckout
  description: Folder for DFaibacheckout
- name: DFaibaAirtimecheckout
  description: Folder for DFaibaAirtimecheckout
